### ISSUE TITLE
feasibility_problem test fail in Julia CI bot

### ISSUE THREAD

**Issue by blegat** [oxfordcontrol/OSQP.jl#35] opened 2018-11-27 16:28 UTC
When running the reverse dependency test for [MOI v0.6.4 release](https://github.com/JuliaLang/METADATA.jl/pull/19749), OSQP failed with Julia v1.0:
https://juliarun-ci.s3.amazonaws.com/ea543accf086b6fbd95b831f07ec87c282fc750f/OSQP_with_pull_request_of_MathOptInterface_on_julia_1_0.log
I cannot reproduce it locally.

**Comment by tkoolen** [comment] 2018-11-27 19:56
This test doesn't involve any MOI-related code, so I don't think the MOI release is related. I also can't reproduce locally (on Julia 1.0.2 though; Travis is running 1.0.0 for some reason).

@bstellato, @gbanjac, any ideas?

**Comment by tkoolen** [comment] 2018-11-27 20:01
Can't reproduce locally with Julia 1.0.0 either.

**Comment by gbanjac** [comment] 2018-11-28 08:44
I cannot reproduce it either. I am using Julia 1.0.2 on Windows.

**Comment by bstellato** [comment] 2019-05-24 13:56
I will close this since it is very old and it does not happen anymore.

**Closed by bstellato** 2019-05-24 13:56 UTC
